#аккуратное завершение работы,
#то есть ожидания окончания обработки запросов
server:
  shutdown: graceful

spring:
  main:
    banner-mode: off
# при аккуратном завершении работы,
# сервер будет ждать завершения работы этих активных запросов
# до указанного промежутка времени
  lifecycle:
    timeout-per-shutdown-phase: 1m



